export const THEME_COLOR_CATALOG = [
  // Brand & Primary
  { "key": "theme_color_primary", "cssVar": "--kryros-primary", "defaultValue": "#C0151B", "label": "Primary", "category": "brand" },
  { "key": "theme_color_primary_hover", "cssVar": "--kryros-primary-hover", "defaultValue": "#A01015", "label": "Primary Hover", "category": "brand" },
  { "key": "theme_color_primary_active", "cssVar": "--kryros-primary-active", "defaultValue": "#8A0F13", "label": "Primary Active", "category": "brand" },
  { "key": "theme_color_secondary", "cssVar": "--kryros-secondary", "defaultValue": "#344a64", "label": "Secondary", "category": "brand" },
  { "key": "theme_color_secondary_bg", "cssVar": "--kryros-secondary-bg", "defaultValue": "#FAFAFA", "label": "Secondary Bg", "category": "brand" },
  { "key": "theme_color_black_primary", "cssVar": "--kryros-black-primary", "defaultValue": "#000000", "label": "Black Primary", "category": "brand" },
  { "key": "theme_color_primary_text", "cssVar": "--kryros-primary-text", "defaultValue": "#313133", "label": "Primary Text", "category": "brand" },
  { "key": "theme_color_secondary_text", "cssVar": "--kryros-secondary-text", "defaultValue": "#75757A", "label": "Secondary Text", "category": "brand" },
  { "key": "theme_color_primary_btn", "cssVar": "--kryros-primary-btn", "defaultValue": "#344a64", "label": "Primary Btn", "category": "brand" },
  { "key": "theme_color_secondary_btn", "cssVar": "--kryros-secondary-btn", "defaultValue": "#C0151B", "label": "Secondary Btn", "category": "brand" },
  { "key": "theme_color_header_navy", "cssVar": "--kryros-header-navy", "defaultValue": "#001529", "label": "Header Navy", "category": "brand" },
  { "key": "theme_color_shadow_primary_sm", "cssVar": "--kryros-shadow-primary-sm", "defaultValue": "rgba(192,21,27,0.18)", "label": "Shadow Primary Sm", "category": "brand" },
  { "key": "theme_color_shadow_primary_md", "cssVar": "--kryros-shadow-primary-md", "defaultValue": "rgba(192,21,27,0.25)", "label": "Shadow Primary Md", "category": "brand" },
  { "key": "theme_color_shadow_primary_lg", "cssVar": "--kryros-shadow-primary-lg", "defaultValue": "rgba(192,21,27,0.30)", "label": "Shadow Primary Lg", "category": "brand" },
  { "key": "theme_color_shadow_primary_btn", "cssVar": "--kryros-shadow-primary-btn", "defaultValue": "rgba(192,21,27,0.45)", "label": "Shadow Primary Btn", "category": "brand" },
  // Buttons
  { "key": "theme_color_dark_btn", "cssVar": "--kryros-dark-btn", "defaultValue": "#313133", "label": "Dark Btn", "category": "button" },
  { "key": "theme_color_disabled_btn", "cssVar": "--kryros-disabled-btn", "defaultValue": "#C7C7CD", "label": "Disabled Btn", "category": "button" },
  // Backgrounds & Surfaces
  { "key": "theme_color_main_bg", "cssVar": "--kryros-main-bg", "defaultValue": "#FFFFFF", "label": "Main Bg", "category": "background" },
  { "key": "theme_color_card_bg", "cssVar": "--kryros-card-bg", "defaultValue": "#FFFFFF", "label": "Card Bg", "category": "background" },
  { "key": "theme_color_footer_bg", "cssVar": "--kryros-footer-bg", "defaultValue": "#000000", "label": "Footer Bg", "category": "background" },
  { "key": "theme_color_overlay", "cssVar": "--kryros-overlay", "defaultValue": "rgba(0,0,0,0.50)", "label": "Overlay", "category": "background" },
  { "key": "theme_color_overlay_dark", "cssVar": "--kryros-overlay-dark", "defaultValue": "rgba(0,0,0,0.62)", "label": "Overlay Dark", "category": "background" },
  { "key": "theme_color_overlay_navy", "cssVar": "--kryros-overlay-navy", "defaultValue": "rgba(15,23,42,0.72)", "label": "Overlay Navy", "category": "background" },
  { "key": "theme_color_overlay_light", "cssVar": "--kryros-overlay-light", "defaultValue": "rgba(255,255,255,0.90)", "label": "Overlay Light", "category": "background" },
  { "key": "theme_color_quantity_bg", "cssVar": "--kryros-quantity-bg", "defaultValue": "#313133", "label": "Quantity Bg", "category": "background" },
  { "key": "theme_color_icon_bg_orders", "cssVar": "--kryros-icon-bg-orders", "defaultValue": "rgba(192,21,27,0.08)", "label": "Icon Bg Orders", "category": "background" },
  { "key": "theme_color_icon_bg_wishlist", "cssVar": "--kryros-icon-bg-wishlist", "defaultValue": "#fdf2f8", "label": "Icon Bg Wishlist", "category": "background" },
  { "key": "theme_color_icon_bg_credit", "cssVar": "--kryros-icon-bg-credit", "defaultValue": "#fff7ed", "label": "Icon Bg Credit", "category": "background" },
  { "key": "theme_color_icon_bg_address", "cssVar": "--kryros-icon-bg-address", "defaultValue": "#f5f3ff", "label": "Icon Bg Address", "category": "background" },
  { "key": "theme_color_warning_bg", "cssVar": "--kryros-warning-bg", "defaultValue": "#fffbeb", "label": "Warning Bg", "category": "background" },
  { "key": "theme_color_page_bg_start", "cssVar": "--kryros-page-bg-start", "defaultValue": "#FAFAFA", "label": "Page Gradient Start", "category": "background" },
  { "key": "theme_color_card_shadow", "cssVar": "--kryros-card-shadow", "defaultValue": "rgba(0,0,0,0.08)", "label": "Card Shadow Color", "category": "background" },
  // Typography & Text
  { "key": "theme_color_white_text", "cssVar": "--kryros-white-text", "defaultValue": "#FFFFFF", "label": "White Text", "category": "text" },
  { "key": "theme_color_disabled_text", "cssVar": "--kryros-disabled-text", "defaultValue": "#9E9E9E", "label": "Disabled Text", "category": "text" },
  { "key": "theme_color_warning_text", "cssVar": "--kryros-warning-text", "defaultValue": "#92400e", "label": "Warning Text", "category": "text" },
  // Borders & Dividers
  { "key": "theme_color_border", "cssVar": "--kryros-border", "defaultValue": "#E5E5E5", "label": "Border", "category": "border" },
  { "key": "theme_color_divider", "cssVar": "--kryros-divider", "defaultValue": "#E5E5E5", "label": "Divider", "category": "border" },
  { "key": "theme_color_border_gray", "cssVar": "--kryros-border-gray", "defaultValue": "#E5E5E5", "label": "Border Gray", "category": "border" },
  { "key": "theme_color_quantity_border", "cssVar": "--kryros-quantity-border", "defaultValue": "#E5E5E5", "label": "Quantity Border", "category": "border" },
  { "key": "theme_color_warning_border", "cssVar": "--kryros-warning-border", "defaultValue": "#fde68a", "label": "Warning Border", "category": "border" },
  // Status & Feedback
  { "key": "theme_color_success", "cssVar": "--kryros-success", "defaultValue": "#2DBE60", "label": "Success", "category": "status" },
  { "key": "theme_color_error", "cssVar": "--kryros-error", "defaultValue": "#D63031", "label": "Error", "category": "status" },
  { "key": "theme_color_warning", "cssVar": "--kryros-warning", "defaultValue": "#F68B1E", "label": "Warning", "category": "status" },
  // Icons & Highlights
  { "key": "theme_color_icon_color_wishlist", "cssVar": "--kryros-icon-color-wishlist", "defaultValue": "#ec4899", "label": "Icon Color Wishlist", "category": "icon" },
  { "key": "theme_color_icon_color_credit", "cssVar": "--kryros-icon-color-credit", "defaultValue": "#f97316", "label": "Icon Color Credit", "category": "icon" },
  { "key": "theme_color_icon_color_address", "cssVar": "--kryros-icon-color-address", "defaultValue": "#8b5cf6", "label": "Icon Color Address", "category": "icon" },
  // Auth & Form Colors
  { "key": "theme_color_form_bg", "cssVar": "--kryros-form-bg", "defaultValue": "#FAFAFA", "label": "Form Background", "category": "form" },
  { "key": "theme_color_form_border", "cssVar": "--kryros-form-border", "defaultValue": "#E5E5E5", "label": "Form Border", "category": "form" },
  { "key": "theme_color_form_text_muted", "cssVar": "--kryros-form-text-muted", "defaultValue": "#75757A", "label": "Form Text Muted", "category": "form" },
  { "key": "theme_color_form_text_hint", "cssVar": "--kryros-form-text-hint", "defaultValue": "#9E9E9E", "label": "Form Text Hint", "category": "form" },
  { "key": "theme_color_form_text_label", "cssVar": "--kryros-form-text-label", "defaultValue": "#A0A0A5", "label": "Form Text Label", "category": "form" },
  { "key": "theme_color_form_error_bg", "cssVar": "--kryros-form-error-bg", "defaultValue": "#FFF0F0", "label": "Form Error Background", "category": "form" },
  { "key": "theme_color_form_error_border", "cssVar": "--kryros-form-error-border", "defaultValue": "#FFD0D0", "label": "Form Error Border", "category": "form" },
  { "key": "theme_color_form_info_bg", "cssVar": "--kryros-form-info-bg", "defaultValue": "#F0F7FF", "label": "Form Info Background", "category": "form" },
  { "key": "theme_color_form_info_border", "cssVar": "--kryros-form-info-border", "defaultValue": "#D0E0F0", "label": "Form Info Border", "category": "form" },
  { "key": "theme_color_form_success_bg", "cssVar": "--kryros-form-success-bg", "defaultValue": "#E8F5E9", "label": "Form Success Background", "category": "form" },
  { "key": "theme_color_form_success_icon", "cssVar": "--kryros-form-success-icon", "defaultValue": "#2DBE60", "label": "Form Success Icon", "category": "form" },
  { "key": "theme_color_form_strength_bar_bg", "cssVar": "--kryros-form-strength-bar-bg", "defaultValue": "#E5E5E5", "label": "Password Strength Bar Bg", "category": "form" },
  // Announcement Bar
  { "key": "theme_color_announcement_text", "cssVar": "--kryros-announcement-text", "defaultValue": "#333333", "label": "Announcement Bar Text", "category": "announcement" },
  { "key": "theme_color_announcement_closed_bg", "cssVar": "--kryros-announcement-closed-bg", "defaultValue": "#dc2626", "label": "Announcement Closed Background", "category": "announcement" },
  { "key": "theme_color_announcement_closed_text", "cssVar": "--kryros-announcement-closed-text", "defaultValue": "#ffffff", "label": "Announcement Closed Text", "category": "announcement" },
  // Social Brand Colors
  { "key": "theme_color_social_facebook", "cssVar": "--kryros-social-facebook", "defaultValue": "#1877F2", "label": "Facebook Brand Color", "category": "social" },
  { "key": "theme_color_social_instagram", "cssVar": "--kryros-social-instagram", "defaultValue": "#E4405F", "label": "Instagram Brand Color", "category": "social" },
  { "key": "theme_color_social_twitter", "cssVar": "--kryros-social-twitter", "defaultValue": "#1DA1F2", "label": "Twitter/X Brand Color", "category": "social" },
  { "key": "theme_color_social_youtube", "cssVar": "--kryros-social-youtube", "defaultValue": "#FF0000", "label": "YouTube Brand Color", "category": "social" },
  // Receipt & Print
  { "key": "theme_color_receipt_bg", "cssVar": "--kryros-receipt-bg", "defaultValue": "#f5f5f5", "label": "Receipt Bg", "category": "receipt" },
  { "key": "theme_color_receipt_card", "cssVar": "--kryros-receipt-card", "defaultValue": "#ffffff", "label": "Receipt Card", "category": "receipt" },
  { "key": "theme_color_receipt_border", "cssVar": "--kryros-receipt-border", "defaultValue": "#f0f0f0", "label": "Receipt Border", "category": "receipt" },
  { "key": "theme_color_receipt_success", "cssVar": "--kryros-receipt-success", "defaultValue": "#22c55e", "label": "Receipt Success", "category": "receipt" },
  { "key": "theme_color_receipt_text_primary", "cssVar": "--kryros-receipt-text-primary", "defaultValue": "#111111", "label": "Receipt Text Primary", "category": "receipt" },
  { "key": "theme_color_receipt_text_secondary", "cssVar": "--kryros-receipt-text-secondary", "defaultValue": "#555555", "label": "Receipt Text Secondary", "category": "receipt" },
  { "key": "theme_color_receipt_label", "cssVar": "--kryros-receipt-label", "defaultValue": "#888888", "label": "Receipt Label", "category": "receipt" },
  { "key": "theme_color_receipt_muted", "cssVar": "--kryros-receipt-muted", "defaultValue": "#aaaaaa", "label": "Receipt Muted", "category": "receipt" },
  { "key": "theme_color_receipt_red", "cssVar": "--kryros-receipt-red", "defaultValue": "#b91c1c", "label": "Receipt Red", "category": "receipt" },
  { "key": "theme_color_receipt_teal", "cssVar": "--kryros-receipt-teal", "defaultValue": "#27B9AF", "label": "Receipt Teal", "category": "receipt" },
  // Other / General
  { "key": "theme_color_white", "cssVar": "--kryros-white", "defaultValue": "#FFFFFF", "label": "White", "category": "general" },
  { "key": "theme_color_light_gray", "cssVar": "--kryros-light-gray", "defaultValue": "#FFFFFF", "label": "Light Gray", "category": "general" },
  { "key": "theme_color_medium_gray", "cssVar": "--kryros-medium-gray", "defaultValue": "#75757A", "label": "Medium Gray", "category": "general" },
  { "key": "theme_color_dark_gray", "cssVar": "--kryros-dark-gray", "defaultValue": "#535357", "label": "Dark Gray", "category": "general" },
  { "key": "theme_color_link", "cssVar": "--kryros-link", "defaultValue": "#2563EB", "label": "Link", "category": "general" },
  { "key": "theme_color_gold", "cssVar": "--kryros-gold", "defaultValue": "#F6B01E", "label": "Gold", "category": "general" },
  { "key": "theme_color_orange_glow", "cssVar": "--kryros-orange-glow", "defaultValue": "rgba(246,139,30,0.15)", "label": "Orange Glow", "category": "general" },
  { "key": "theme_color_shadow", "cssVar": "--kryros-shadow", "defaultValue": "rgba(0,0,0,0.10)", "label": "Shadow", "category": "general" },
  { "key": "theme_color_shadow_subtle", "cssVar": "--kryros-shadow-subtle", "defaultValue": "rgba(15,23,42,0.04)", "label": "Shadow Subtle", "category": "general" },
  { "key": "theme_color_accent_purple", "cssVar": "--kryros-accent-purple", "defaultValue": "#7C3AED", "label": "Accent Purple", "category": "general" },
  { "key": "theme_color_whatsapp", "cssVar": "--kryros-whatsapp", "defaultValue": "#25D366", "label": "WhatsApp", "category": "general" },
  { "key": "theme_color_map_marker", "cssVar": "--kryros-map-marker", "defaultValue": "#0ea5e9", "label": "Map Marker", "category": "general" },
  { "key": "theme_color_star_filled", "cssVar": "--kryros-star-filled", "defaultValue": "#FFC107", "label": "Star Filled", "category": "general" },
];
