import { PrismaClient, SymbolPosition } from '@prisma/client';

const prisma = new PrismaClient();

const countries = [
  { name: 'Afghanistan', code: 'AF', currency: 'AFN', symbol: '؋', pos: 'BEFORE', flag: '🇦🇫' },
  { name: 'Albania', code: 'AL', currency: 'ALL', symbol: 'Lek', pos: 'AFTER', flag: '🇦🇱' },
  { name: 'Algeria', code: 'DZ', currency: 'DZD', symbol: 'دج', pos: 'BEFORE', flag: '🇩🇿' },
  { name: 'Andorra', code: 'AD', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇦🇩' },
  { name: 'Angola', code: 'AO', currency: 'AOA', symbol: 'Kz', pos: 'BEFORE', flag: '🇦🇴' },
  { name: 'Antigua and Barbuda', code: 'AG', currency: 'XCD', symbol: '$', pos: 'BEFORE', flag: '🇦🇬' },
  { name: 'Argentina', code: 'AR', currency: 'ARS', symbol: '$', pos: 'BEFORE', flag: '🇦🇷' },
  { name: 'Armenia', code: 'AM', currency: 'AMD', symbol: '֏', pos: 'AFTER', flag: '🇦🇲' },
  { name: 'Australia', code: 'AU', currency: 'AUD', symbol: '$', pos: 'BEFORE', flag: '🇦🇺' },
  { name: 'Austria', code: 'AT', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZ', currency: 'AZN', symbol: '₼', pos: 'AFTER', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', currency: 'BSD', symbol: '$', pos: 'BEFORE', flag: '🇧🇸' },
  { name: 'Bahrain', code: 'BH', currency: 'BHD', symbol: '.د.ب', pos: 'BEFORE', flag: '🇧🇭' },
  { name: 'Bangladesh', code: 'BD', currency: 'BDT', symbol: '৳', pos: 'BEFORE', flag: '🇧🇩' },
  { name: 'Barbados', code: 'BB', currency: 'BBD', symbol: '$', pos: 'BEFORE', flag: '🇧🇧' },
  { name: 'Belarus', code: 'BY', currency: 'BYN', symbol: 'Br', pos: 'AFTER', flag: '🇧🇾' },
  { name: 'Belgium', code: 'BE', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇧🇪' },
  { name: 'Belize', code: 'BZ', currency: 'BZD', symbol: '$', pos: 'BEFORE', flag: '🇧🇿' },
  { name: 'Benin', code: 'BJ', currency: 'XOF', symbol: 'CFA', pos: 'AFTER', flag: '🇧🇯' },
  { name: 'Bhutan', code: 'BT', currency: 'BTN', symbol: 'Nu.', pos: 'BEFORE', flag: '🇧🇹' },
  { name: 'Bolivia', code: 'BO', currency: 'BOB', symbol: 'Bs.', pos: 'BEFORE', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: 'BA', currency: 'BAM', symbol: 'KM', pos: 'AFTER', flag: '🇧🇦' },
  { name: 'Botswana', code: 'BW', currency: 'BWP', symbol: 'P', pos: 'BEFORE', flag: '🇧🇼' },
  { name: 'Brazil', code: 'BR', currency: 'BRL', symbol: 'R$', pos: 'BEFORE', flag: '🇧🇷' },
  { name: 'Brunei', code: 'BN', currency: 'BND', symbol: '$', pos: 'BEFORE', flag: '🇧🇳' },
  { name: 'Bulgaria', code: 'BG', currency: 'BGN', symbol: 'лв.', pos: 'AFTER', flag: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BF', currency: 'XOF', symbol: 'CFA', pos: 'AFTER', flag: '🇧🇫' },
  { name: 'Burundi', code: 'BI', currency: 'BIF', symbol: 'FBu', pos: 'AFTER', flag: '🇧🇮' },
  { name: 'Cabo Verde', code: 'CV', currency: 'CVE', symbol: '$', pos: 'AFTER', flag: '🇨🇻' },
  { name: 'Cambodia', code: 'KH', currency: 'KHR', symbol: '៛', pos: 'BEFORE', flag: '🇰🇭' },
  { name: 'Cameroon', code: 'CM', currency: 'XAF', symbol: 'CFA', pos: 'AFTER', flag: '🇨🇲' },
  { name: 'Canada', code: 'CA', currency: 'CAD', symbol: '$', pos: 'BEFORE', flag: '🇨🇦' },
  { name: 'Central African Republic', code: 'CF', currency: 'XAF', symbol: 'CFA', pos: 'AFTER', flag: '🇨🇫' },
  { name: 'Chad', code: 'TD', currency: 'XAF', symbol: 'CFA', pos: 'AFTER', flag: '🇹🇩' },
  { name: 'Chile', code: 'CL', currency: 'CLP', symbol: '$', pos: 'BEFORE', flag: '🇨🇱' },
  { name: 'China', code: 'CN', currency: 'CNY', symbol: '¥', pos: 'BEFORE', flag: '🇨🇳' },
  { name: 'Colombia', code: 'CO', currency: 'COP', symbol: '$', pos: 'BEFORE', flag: '🇨🇴' },
  { name: 'Comoros', code: 'KM', currency: 'KMF', symbol: 'CF', pos: 'AFTER', flag: '🇰🇲' },
  { name: 'Congo (Brazzaville)', code: 'CG', currency: 'XAF', symbol: 'CFA', pos: 'AFTER', flag: '🇨🇬' },
  { name: 'Congo (Kinshasa)', code: 'CD', currency: 'CDF', symbol: 'FC', pos: 'AFTER', flag: '🇨🇩' },
  { name: 'Costa Rica', code: 'CR', currency: 'CRC', symbol: '₡', pos: 'BEFORE', flag: '🇨🇷' },
  { name: 'Croatia', code: 'HR', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇭🇷' },
  { name: 'Cuba', code: 'CU', currency: 'CUP', symbol: '$', pos: 'BEFORE', flag: '🇨🇺' },
  { name: 'Cyprus', code: 'CY', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZ', currency: 'CZK', symbol: 'Kč', pos: 'AFTER', flag: '🇨🇿' },
  { name: 'Denmark', code: 'DK', currency: 'DKK', symbol: 'kr.', pos: 'AFTER', flag: '🇩🇰' },
  { name: 'Djibouti', code: 'DJ', currency: 'DJF', symbol: 'Fdj', pos: 'AFTER', flag: '🇩🇯' },
  { name: 'Dominica', code: 'DM', currency: 'XCD', symbol: '$', pos: 'BEFORE', flag: '🇩🇲' },
  { name: 'Dominican Republic', code: 'DO', currency: 'DOP', symbol: '$', pos: 'BEFORE', flag: '🇩🇴' },
  { name: 'Ecuador', code: 'EC', currency: 'USD', symbol: '$', pos: 'BEFORE', flag: '🇪🇨' },
  { name: 'Egypt', code: 'EG', currency: 'EGP', symbol: 'E£', pos: 'BEFORE', flag: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', currency: 'USD', symbol: '$', pos: 'BEFORE', flag: '🇸🇻' },
  { name: 'Equatorial Guinea', code: 'GQ', currency: 'XAF', symbol: 'CFA', pos: 'AFTER', flag: '🇬🇶' },
  { name: 'Eritrea', code: 'ER', currency: 'ERN', symbol: 'Nfk', pos: 'AFTER', flag: '🇪🇷' },
  { name: 'Estonia', code: 'EE', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇪🇪' },
  { name: 'Eswatini', code: 'SZ', currency: 'SZL', symbol: 'L', pos: 'BEFORE', flag: '🇸🇿' },
  { name: 'Ethiopia', code: 'ET', currency: 'ETB', symbol: 'Br', pos: 'BEFORE', flag: '🇪🇹' },
  { name: 'Fiji', code: 'FJ', currency: 'FJD', symbol: '$', pos: 'BEFORE', flag: '🇫🇯' },
  { name: 'Finland', code: 'FI', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇫🇮' },
  { name: 'France', code: 'FR', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇫🇷' },
  { name: 'Gabon', code: 'GA', currency: 'XAF', symbol: 'CFA', pos: 'AFTER', flag: '🇬🇦' },
  { name: 'Gambia', code: 'GM', currency: 'GMD', symbol: 'D', pos: 'BEFORE', flag: '🇬🇲' },
  { name: 'Georgia', code: 'GE', currency: 'GEL', symbol: '₾', pos: 'AFTER', flag: '🇬🇪' },
  { name: 'Germany', code: 'DE', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇩🇪' },
  { name: 'Ghana', code: 'GH', currency: 'GHS', symbol: 'GH₵', pos: 'BEFORE', flag: '🇬🇭' },
  { name: 'Greece', code: 'GR', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇬🇷' },
  { name: 'Grenada', code: 'GD', currency: 'XCD', symbol: '$', pos: 'BEFORE', flag: '🇬🇩' },
  { name: 'Guatemala', code: 'GT', currency: 'GTQ', symbol: 'Q', pos: 'BEFORE', flag: '🇬🇹' },
  { name: 'Guinea', code: 'GN', currency: 'GNF', symbol: 'FG', pos: 'AFTER', flag: '🇬🇳' },
  { name: 'Guinea-Bissau', code: 'GW', currency: 'XOF', symbol: 'CFA', pos: 'AFTER', flag: '🇬🇼' },
  { name: 'Guyana', code: 'GY', currency: 'GYD', symbol: '$', pos: 'BEFORE', flag: '🇬🇾' },
  { name: 'Haiti', code: 'HT', currency: 'HTG', symbol: 'G', pos: 'BEFORE', flag: '🇭🇹' },
  { name: 'Honduras', code: 'HN', currency: 'HNL', symbol: 'L', pos: 'BEFORE', flag: '🇭🇳' },
  { name: 'Hungary', code: 'HU', currency: 'HUF', symbol: 'Ft', pos: 'AFTER', flag: '🇭🇺' },
  { name: 'Iceland', code: 'IS', currency: 'ISK', symbol: 'kr', pos: 'AFTER', flag: '🇮🇸' },
  { name: 'India', code: 'IN', currency: 'INR', symbol: '₹', pos: 'BEFORE', flag: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', currency: 'IDR', symbol: 'Rp', pos: 'BEFORE', flag: '🇮🇩' },
  { name: 'Iran', code: 'IR', currency: 'IRR', symbol: '﷼', pos: 'BEFORE', flag: '🇮🇷' },
  { name: 'Iraq', code: 'IQ', currency: 'IQD', symbol: 'ع.د', pos: 'BEFORE', flag: '🇮🇶' },
  { name: 'Ireland', code: 'IE', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇮🇪' },
  { name: 'Israel', code: 'IL', currency: 'ILS', symbol: '₪', pos: 'BEFORE', flag: '🇮🇱' },
  { name: 'Italy', code: 'IT', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇮🇹' },
  { name: 'Jamaica', code: 'JM', currency: 'JMD', symbol: '$', pos: 'BEFORE', flag: '🇯🇲' },
  { name: 'Japan', code: 'JP', currency: 'JPY', symbol: '¥', pos: 'BEFORE', flag: '🇯🇵' },
  { name: 'Jordan', code: 'JO', currency: 'JOD', symbol: 'د.ا', pos: 'BEFORE', flag: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KZ', currency: 'KZT', symbol: '₸', pos: 'BEFORE', flag: '🇰🇿' },
  { name: 'Kenya', code: 'KE', currency: 'KES', symbol: 'KSh', pos: 'BEFORE', flag: '🇰🇪' },
  { name: 'Kiribati', code: 'KI', currency: 'AUD', symbol: '$', pos: 'BEFORE', flag: '🇰🇮' },
  { name: 'Korea, North', code: 'KP', currency: 'KPW', symbol: '₩', pos: 'BEFORE', flag: '🇰🇵' },
  { name: 'Korea, South', code: 'KR', currency: 'KRW', symbol: '₩', pos: 'BEFORE', flag: '🇰🇷' },
  { name: 'Kuwait', code: 'KW', currency: 'KWD', symbol: 'د.ك', pos: 'BEFORE', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KG', currency: 'KGS', symbol: 'с', pos: 'AFTER', flag: '🇰🇬' },
  { name: 'Laos', code: 'LA', currency: 'LAK', symbol: '₭', pos: 'BEFORE', flag: '🇱🇦' },
  { name: 'Latvia', code: 'LV', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇱🇻' },
  { name: 'Lebanon', code: 'LB', currency: 'LBP', symbol: 'L£', pos: 'BEFORE', flag: '🇱🇧' },
  { name: 'Lesotho', code: 'LS', currency: 'LSL', symbol: 'L', pos: 'BEFORE', flag: '🇱🇸' },
  { name: 'Liberia', code: 'LR', currency: 'LRD', symbol: '$', pos: 'BEFORE', flag: '🇱🇷' },
  { name: 'Libya', code: 'LY', currency: 'LYD', symbol: 'ل.د', pos: 'BEFORE', flag: '🇱🇾' },
  { name: 'Liechtenstein', code: 'LI', currency: 'CHF', symbol: 'CHF', pos: 'BEFORE', flag: '🇱🇮' },
  { name: 'Lithuania', code: 'LT', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇱🇹' },
  { name: 'Luxembourg', code: 'LU', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇱🇺' },
  { name: 'Madagascar', code: 'MG', currency: 'MGA', symbol: 'Ar', pos: 'BEFORE', flag: '🇲🇬' },
  { name: 'Malawi', code: 'MW', currency: 'MWK', symbol: 'MK', pos: 'BEFORE', flag: '🇲🇼' },
  { name: 'Malaysia', code: 'MY', currency: 'MYR', symbol: 'RM', pos: 'BEFORE', flag: '🇲🇾' },
  { name: 'Maldives', code: 'MV', currency: 'MVR', symbol: 'Rf', pos: 'AFTER', flag: '🇲🇻' },
  { name: 'Mali', code: 'ML', currency: 'XOF', symbol: 'CFA', pos: 'AFTER', flag: '🇲🇱' },
  { name: 'Malta', code: 'MT', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇲🇹' },
  { name: 'Marshall Islands', code: 'MH', currency: 'USD', symbol: '$', pos: 'BEFORE', flag: '🇲🇭' },
  { name: 'Mauritania', code: 'MR', currency: 'MRU', symbol: 'UM', pos: 'AFTER', flag: '🇲🇷' },
  { name: 'Mauritius', code: 'MU', currency: 'MUR', symbol: '₨', pos: 'BEFORE', flag: '🇲🇺' },
  { name: 'Mexico', code: 'MX', currency: 'MXN', symbol: '$', pos: 'BEFORE', flag: '🇲🇽' },
  { name: 'Micronesia', code: 'FM', currency: 'USD', symbol: '$', pos: 'BEFORE', flag: '🇫🇲' },
  { name: 'Moldova', code: 'MD', currency: 'MDL', symbol: 'L', pos: 'AFTER', flag: '🇲🇩' },
  { name: 'Monaco', code: 'MC', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇲🇨' },
  { name: 'Mongolia', code: 'MN', currency: 'MNT', symbol: '₮', pos: 'BEFORE', flag: '🇲🇳' },
  { name: 'Montenegro', code: 'ME', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇲🇪' },
  { name: 'Morocco', code: 'MA', currency: 'MAD', symbol: 'د.م.', pos: 'BEFORE', flag: '🇲🇦' },
  { name: 'Mozambique', code: 'MZ', currency: 'MZN', symbol: 'MT', pos: 'BEFORE', flag: '🇲🇿' },
  { name: 'Myanmar', code: 'MM', currency: 'MMK', symbol: 'K', pos: 'BEFORE', flag: '🇲🇲' },
  { name: 'Namibia', code: 'NA', currency: 'NAD', symbol: '$', pos: 'BEFORE', flag: '🇳🇦' },
  { name: 'Nauru', code: 'NR', currency: 'AUD', symbol: '$', pos: 'BEFORE', flag: '🇳🇷' },
  { name: 'Nepal', code: 'NP', currency: 'NPR', symbol: '₨', pos: 'BEFORE', flag: '🇳🇵' },
  { name: 'Netherlands', code: 'NL', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇳🇱' },
  { name: 'New Zealand', code: 'NZ', currency: 'NZD', symbol: '$', pos: 'BEFORE', flag: '🇳🇿' },
  { name: 'Nicaragua', code: 'NI', currency: 'NIO', symbol: 'C$', pos: 'BEFORE', flag: '🇳🇮' },
  { name: 'Niger', code: 'NE', currency: 'XOF', symbol: 'CFA', pos: 'AFTER', flag: '🇳🇪' },
  { name: 'Nigeria', code: 'NG', currency: 'NGN', symbol: '₦', pos: 'BEFORE', flag: '🇳🇬' },
  { name: 'North Macedonia', code: 'MK', currency: 'MKD', symbol: 'ден', pos: 'AFTER', flag: '🇲🇰' },
  { name: 'Norway', code: 'NO', currency: 'NOK', symbol: 'kr', pos: 'AFTER', flag: '🇳🇴' },
  { name: 'Oman', code: 'OM', currency: 'OMR', symbol: 'ر.ع.', pos: 'BEFORE', flag: '🇴🇲' },
  { name: 'Pakistan', code: 'PK', currency: 'PKR', symbol: '₨', pos: 'BEFORE', flag: '🇵🇰' },
  { name: 'Palau', code: 'PW', currency: 'USD', symbol: '$', pos: 'BEFORE', flag: '🇵🇼' },
  { name: 'Panama', code: 'PA', currency: 'PAB', symbol: 'B/.', pos: 'BEFORE', flag: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'PG', currency: 'PGK', symbol: 'K', pos: 'BEFORE', flag: '🇵🇬' },
  { name: 'Paraguay', code: 'PY', currency: 'PYG', symbol: '₲', pos: 'BEFORE', flag: '🇵🇾' },
  { name: 'Peru', code: 'PE', currency: 'PEN', symbol: 'S/.', pos: 'BEFORE', flag: '🇵🇪' },
  { name: 'Philippines', code: 'PH', currency: 'PHP', symbol: '₱', pos: 'BEFORE', flag: '🇵🇭' },
  { name: 'Poland', code: 'PL', currency: 'PLN', symbol: 'zł', pos: 'AFTER', flag: '🇵🇱' },
  { name: 'Portugal', code: 'PT', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇵🇹' },
  { name: 'Qatar', code: 'QA', currency: 'QAR', symbol: 'ر.ق', pos: 'BEFORE', flag: '🇶🇦' },
  { name: 'Romania', code: 'RO', currency: 'RON', symbol: 'lei', pos: 'AFTER', flag: '🇷🇴' },
  { name: 'Russia', code: 'RU', currency: 'RUB', symbol: '₽', pos: 'AFTER', flag: '🇷🇺' },
  { name: 'Rwanda', code: 'RW', currency: 'RWF', symbol: 'FRw', pos: 'AFTER', flag: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', code: 'KN', currency: 'XCD', symbol: '$', pos: 'BEFORE', flag: '🇰🇳' },
  { name: 'Saint Lucia', code: 'LC', currency: 'XCD', symbol: '$', pos: 'BEFORE', flag: '🇱🇨' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', currency: 'XCD', symbol: '$', pos: 'BEFORE', flag: '🇻🇨' },
  { name: 'Samoa', code: 'WS', currency: 'WST', symbol: 'T', pos: 'BEFORE', flag: '🇼🇸' },
  { name: 'San Marino', code: 'SM', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇸🇲' },
  { name: 'Sao Tome and Principe', code: 'ST', currency: 'STN', symbol: 'Db', pos: 'BEFORE', flag: '🇸🇹' },
  { name: 'Saudi Arabia', code: 'SA', currency: 'SAR', symbol: 'ر.س', pos: 'BEFORE', flag: '🇸🇦' },
  { name: 'Senegal', code: 'SN', currency: 'XOF', symbol: 'CFA', pos: 'AFTER', flag: '🇸🇳' },
  { name: 'Serbia', code: 'RS', currency: 'RSD', symbol: 'дин.', pos: 'AFTER', flag: '🇷🇸' },
  { name: 'Seychelles', code: 'SC', currency: 'SCR', symbol: '₨', pos: 'BEFORE', flag: '🇸🇨' },
  { name: 'Sierra Leone', code: 'SL', currency: 'SLL', symbol: 'Le', pos: 'BEFORE', flag: '🇸🇱' },
  { name: 'Singapore', code: 'SG', currency: 'SGD', symbol: '$', pos: 'BEFORE', flag: '🇸🇬' },
  { name: 'Slovakia', code: 'SK', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇸🇰' },
  { name: 'Slovenia', code: 'SI', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇸🇮' },
  { name: 'Solomon Islands', code: 'SB', currency: 'SBD', symbol: '$', pos: 'BEFORE', flag: '🇸🇧' },
  { name: 'Somalia', code: 'SO', currency: 'SOS', symbol: 'Sh', pos: 'BEFORE', flag: '🇸🇴' },
  { name: 'South Africa', code: 'ZA', currency: 'ZAR', symbol: 'R', pos: 'BEFORE', flag: '🇿🇦' },
  { name: 'South Sudan', code: 'SS', currency: 'SSP', symbol: '£', pos: 'BEFORE', flag: '🇸🇸' },
  { name: 'Spain', code: 'ES', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', currency: 'LKR', symbol: 'Rs', pos: 'BEFORE', flag: '🇱🇰' },
  { name: 'Sudan', code: 'SD', currency: 'SDG', symbol: 'ج.س.', pos: 'BEFORE', flag: '🇸🇩' },
  { name: 'Suriname', code: 'SR', currency: 'SRD', symbol: '$', pos: 'BEFORE', flag: '🇸🇷' },
  { name: 'Sweden', code: 'SE', currency: 'SEK', symbol: 'kr', pos: 'AFTER', flag: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', currency: 'CHF', symbol: 'CHF', pos: 'BEFORE', flag: '🇨🇭' },
  { name: 'Syria', code: 'SY', currency: 'SYP', symbol: '£', pos: 'BEFORE', flag: '🇸🇾' },
  { name: 'Taiwan', code: 'TW', currency: 'TWD', symbol: '$', pos: 'BEFORE', flag: '🇹🇼' },
  { name: 'Tajikistan', code: 'TJ', currency: 'TJS', symbol: 'ЅМ', pos: 'AFTER', flag: '🇹🇯' },
  { name: 'Tanzania', code: 'TZ', currency: 'TZS', symbol: 'TSh', pos: 'BEFORE', flag: '🇹🇿' },
  { name: 'Thailand', code: 'TH', currency: 'THB', symbol: '฿', pos: 'BEFORE', flag: '🇹🇭' },
  { name: 'Timor-Leste', code: 'TL', currency: 'USD', symbol: '$', pos: 'BEFORE', flag: '🇹🇱' },
  { name: 'Togo', code: 'TG', currency: 'XOF', symbol: 'CFA', pos: 'AFTER', flag: '🇹🇬' },
  { name: 'Tonga', code: 'TO', currency: 'TOP', symbol: 'T$', pos: 'BEFORE', flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: 'TT', currency: 'TTD', symbol: '$', pos: 'BEFORE', flag: '🇹🇹' },
  { name: 'Tunisia', code: 'TN', currency: 'TND', symbol: 'د.ت', pos: 'BEFORE', flag: '🇹🇳' },
  { name: 'Turkey', code: 'TR', currency: 'TRY', symbol: '₺', pos: 'BEFORE', flag: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TM', currency: 'TMT', symbol: 'm', pos: 'AFTER', flag: '🇹🇲' },
  { name: 'Tuvalu', code: 'TV', currency: 'AUD', symbol: '$', pos: 'BEFORE', flag: '🇹🇻' },
  { name: 'Uganda', code: 'UG', currency: 'UGX', symbol: 'USh', pos: 'BEFORE', flag: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', currency: 'UAH', symbol: '₴', pos: 'AFTER', flag: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'AE', currency: 'AED', symbol: 'د.إ', pos: 'BEFORE', flag: '🇦🇪' },
  { name: 'United Kingdom', code: 'GB', currency: 'GBP', symbol: '£', pos: 'BEFORE', flag: '🇬🇧' },
  { name: 'United States', code: 'US', currency: 'USD', symbol: '$', pos: 'BEFORE', flag: '🇺🇸' },
  { name: 'Uruguay', code: 'UY', currency: 'UYU', symbol: '$', pos: 'BEFORE', flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZ', currency: 'UZS', symbol: 'soʻm', pos: 'AFTER', flag: '🇺🇿' },
  { name: 'Vanuatu', code: 'VU', currency: 'VUV', symbol: 'Vt', pos: 'BEFORE', flag: '🇻🇺' },
  { name: 'Vatican City', code: 'VA', currency: 'EUR', symbol: '€', pos: 'BEFORE', flag: '🇻🇦' },
  { name: 'Venezuela', code: 'VE', currency: 'VES', symbol: 'Bs.S', pos: 'BEFORE', flag: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', currency: 'VND', symbol: '₫', pos: 'AFTER', flag: '🇻🇳' },
  { name: 'Yemen', code: 'YE', currency: 'YER', symbol: '﷼', pos: 'BEFORE', flag: '🇾🇪' },
  { name: 'Zambia', code: 'ZM', currency: 'ZMW', symbol: 'ZK', pos: 'BEFORE', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', currency: 'ZWL', symbol: '$', pos: 'BEFORE', flag: '🇿🇼' },
];

async function main() {
  console.log('Starting world countries seed...');

  for (const c of countries) {
    await prisma.country.upsert({
      where: { code: c.code },
      update: {
        name: c.name,
        currencyCode: c.currency,
        currencySymbol: c.symbol,
        symbolPosition: c.pos === 'BEFORE' ? SymbolPosition.BEFORE : SymbolPosition.AFTER,
        flag: c.flag,
        // Don't overwrite status or exchangeRate if they already exist
      },
      create: {
        name: c.name,
        code: c.code,
        currencyCode: c.currency,
        currencySymbol: c.symbol,
        symbolPosition: c.pos === 'BEFORE' ? SymbolPosition.BEFORE : SymbolPosition.AFTER,
        flag: c.flag,
        exchangeRate: 1.0,
        status: false, // Default to disabled, admin enables them
        shippingEnabled: false,
      },
    });
  }

  console.log(`Seeded ${countries.length} countries.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
